/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Exception.CampoVazioException;
import Exception.CpfIgualException;
import Exception.EmailInválidoException;
import Exception.SomenteNumerosExceptionCPF;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import models.Funcionario;
/**
 *
 * @author levan
 */
public class JFCadastrarLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFAddFuncionario
     */
    public JFCadastrarLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeFuncionario = new javax.swing.JLabel();
        txtCPFFuncionario = new javax.swing.JLabel();
        txtCargoFuncionario = new javax.swing.JLabel();
        txtEmailFuncionario = new javax.swing.JLabel();
        btnSalvarFuncionario = new javax.swing.JButton();
        txtAddNovoFuncionario = new javax.swing.JLabel();
        jTextFieldNomeFuncionario = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldCargoFuncionario = new javax.swing.JTextField();
        jTextFieldEmailFuncionario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar novo funcionário");

        txtNomeFuncionario.setText("Nome:");

        txtCPFFuncionario.setText("CPF:");

        txtCargoFuncionario.setText("Cargo:");

        txtEmailFuncionario.setText("Email:");

        btnSalvarFuncionario.setText("Salvar ");

        txtAddNovoFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAddNovoFuncionario.setText("Cadastro Login:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnSalvarFuncionario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddNovoFuncionario)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCPFFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNomeFuncionario)
                                .addComponent(txtEmailFuncionario)
                                .addComponent(jTextFieldNomeFuncionario)
                                .addComponent(jTextFieldCPF)
                                .addComponent(jTextFieldCargoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(jTextFieldEmailFuncionario)
                                .addComponent(txtCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtAddNovoFuncionario)
                .addGap(27, 27, 27)
                .addComponent(txtNomeFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(txtCPFFuncionario)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCargoFuncionario)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmailFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnSalvarFuncionario)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void addAcaoSalvarFunc(ActionListener acao){
        btnSalvarFuncionario.addActionListener(acao);
    }
    
        
    public void mostrarMsg(String msg) {
        JOptionPane.showMessageDialog(null, msg);
        }

    public Funcionario returnFunc() throws  CpfIgualException, CampoVazioException, 
            SomenteNumerosExceptionCPF, EmailInválidoException{
        String nome = jTextFieldNomeFuncionario.getText();
        String cpf =  jTextFieldCPF.getText();
        String email = jTextFieldEmailFuncionario.getText();
        String cargo = jTextFieldCargoFuncionario.getText();
        
        Funcionario f = new Funcionario();
        f.setNome(nome);
        f.setCpf(cpf);
        f.setEmail(email);
        f.setCargo(cargo);
      
        return f;
    }  
   
    public void limparTela(){
        jTextFieldCPF.setText("");
        jTextFieldCargoFuncionario.setText("");
        jTextFieldEmailFuncionario.setText("");
        jTextFieldNomeFuncionario.setText("");
    }
    
     public void exbirTela(){
        setVisible(true);
    }
     public void fecharTela(){
         this.dispose();
     }

    
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarFuncionario;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCargoFuncionario;
    private javax.swing.JTextField jTextFieldEmailFuncionario;
    private javax.swing.JTextField jTextFieldNomeFuncionario;
    private javax.swing.JLabel txtAddNovoFuncionario;
    private javax.swing.JLabel txtCPFFuncionario;
    private javax.swing.JLabel txtCargoFuncionario;
    private javax.swing.JLabel txtEmailFuncionario;
    private javax.swing.JLabel txtNomeFuncionario;
    // End of variables declaration//GEN-END:variables
}
