/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ClienteDAO;
import DAO.FuncionarioDAO;
import Repositorio.ClienteRepositorio;
import Repositorio.FuncionarioRepositorio;
import java.awt.event.ActionListener;
import java.util.Comparator;
import java.util.List;
import models.Cliente;
import models.Funcionario;
import models.LivroNovo;
import models.LivroUsado;

/**
 *
 * @author LRodrigues
 */
public class JFFuncionarioList extends javax.swing.JFrame {

    FuncionarioRepositorio fr = new FuncionarioDAO();

    /**
     * Creates new form JFListFuncionario
     */
    public JFFuncionarioList() {
        initComponents();
        initComboFuncionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaFuncionarios = new javax.swing.JTextArea();
        cbRemoverFunc = new javax.swing.JComboBox<>();
        BtnAddFuncionario = new javax.swing.JButton();
        btnLimparTela = new javax.swing.JButton();
        btnListFuncionario = new javax.swing.JButton();
        btnRemoverFuncionario = new javax.swing.JButton();
        btnPaginaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtAreaFuncionarios.setColumns(20);
        txtAreaFuncionarios.setRows(5);
        jScrollPane1.setViewportView(txtAreaFuncionarios);

        BtnAddFuncionario.setText("Cadastrar Funcionario");

        btnLimparTela.setText("Limpar Tela");

        btnListFuncionario.setText("Listar Funcionario");

        btnRemoverFuncionario.setText("Remover Funcionario");

        btnPaginaInicial.setText("Pagina Inicial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnAddFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(btnLimparTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnRemoverFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(cbRemoverFunc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(btnPaginaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAddFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(btnListFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparTela)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRemoverFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverFuncionario))
                .addGap(18, 18, 18)
                .addComponent(btnPaginaInicial)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void adicionarAcaoBtnAddFuncionario(ActionListener acao){
        BtnAddFuncionario.addActionListener(acao);
    }

    public void adicionarAcaobtnPaginaInicial(ActionListener acao){
        btnPaginaInicial.addActionListener(acao);
    }

    public void adicionarAcaobtnListFuncionario(ActionListener acao){
        btnListFuncionario.addActionListener(acao);
    }

    public void adicionarAcaobtnLimparTela(ActionListener acao){
        btnLimparTela.addActionListener(acao);
    }

    public void adicionarAcaobtnRemoverFuncionario(ActionListener acao){
        btnRemoverFuncionario.addActionListener(acao);
    }

    public void limparTela() {
        txtAreaFuncionarios.setText("");
    }
    
    public void exibirTela(){
        setVisible(true);
    }
    public void fecharTela(){
        this.dispose();
    }
    
    public void populaDadosListaFuncionario(List<Funcionario> funcionarios) {
        for (Funcionario funcionario : funcionarios) {
            txtAreaFuncionarios.append(funcionario.toString() + "\n");
        }
    }
    /**
     * @param args the command line arguments
     */
    public void initComboFuncionario() {
        List<Funcionario> funcionarios = fr.getTodosFuncionarios();
        for (Funcionario f : funcionarios) {
            cbRemoverFunc.addItem(f);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddFuncionario;
    private javax.swing.JButton btnLimparTela;
    private javax.swing.JButton btnListFuncionario;
    private javax.swing.JButton btnPaginaInicial;
    private javax.swing.JButton btnRemoverFuncionario;
    private javax.swing.JComboBox<Funcionario> cbRemoverFunc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaFuncionarios;
    // End of variables declaration//GEN-END:variables
}
