/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.FuncionarioDAO;
import Repositorio.FuncionarioRepositorio;
import java.util.Comparator;
import java.util.List;
import models.Funcionario;
import models.LivroNovo;
import models.LivroUsado;

/**
 *
 * @author LRodrigues
 */
public class JFFuncionarioList extends javax.swing.JFrame {
    FuncionarioRepositorio fr = new FuncionarioDAO();
    /**
     * Creates new form JFListFuncionario
     */
    public JFFuncionarioList() {
        initComponents();
        initComboFuncionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaFuncionarios = new javax.swing.JTextArea();
        btnListFornecedor = new javax.swing.JButton();
        btnRemoverFunc = new javax.swing.JButton();
        cbRemoverFunc = new javax.swing.JComboBox<>();
        btnLimparTempa = new javax.swing.JButton();
        btnAddFornecedor = new javax.swing.JButton();
        btnTelaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtAreaFuncionarios.setColumns(20);
        txtAreaFuncionarios.setRows(5);
        jScrollPane1.setViewportView(txtAreaFuncionarios);

        btnListFornecedor.setText("Listar Funcionario");
        btnListFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListFornecedorActionPerformed(evt);
            }
        });

        btnRemoverFunc.setText("Remover Funcionário");
        btnRemoverFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFuncActionPerformed(evt);
            }
        });

        btnLimparTempa.setText("Limpar Tela");
        btnLimparTempa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTempaActionPerformed(evt);
            }
        });

        btnAddFornecedor.setText("Adicionar Funcionário");
        btnAddFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFornecedorActionPerformed(evt);
            }
        });

        btnTelaInicial.setText("Tela Inicial");
        btnTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoverFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimparTempa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(cbRemoverFunc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(btnTelaInicial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddFornecedor)
                        .addGap(18, 18, 18)
                        .addComponent(btnListFornecedor)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparTempa))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRemoverFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverFunc))
                .addGap(26, 26, 26)
                .addComponent(btnTelaInicial)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFornecedorActionPerformed
       JFAddFuncionario addFuncionario = new JFAddFuncionario();
        addFuncionario.setVisible(true);
    }//GEN-LAST:event_btnAddFornecedorActionPerformed

    private void btnTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicialActionPerformed
        JFTelaInicial fTelaInicial = new JFTelaInicial();
        fTelaInicial.setVisible(true);
    }//GEN-LAST:event_btnTelaInicialActionPerformed

    private void btnListFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListFornecedorActionPerformed
      FuncionarioRepositorio fr = new FuncionarioDAO();
      
      fr.getTodosFuncionarios().sort((new Comparator<Funcionario>() {
          @Override
          public int compare(Funcionario o1, Funcionario o2) { return o1.getNome().compareTo(o2.getNome());
          }
      }));
      for(Funcionario funcionario : fr.getTodosFuncionarios()){
          txtAreaFuncionarios.append(funcionario.toString()+"\n");
          
      }
    }//GEN-LAST:event_btnListFornecedorActionPerformed

    private void btnLimparTempaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTempaActionPerformed
       txtAreaFuncionarios.setText("");
    }//GEN-LAST:event_btnLimparTempaActionPerformed

    private void btnRemoverFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFuncActionPerformed
//       FuncionarioRepositorio fr = new FuncionarioDAO();
       Funcionario f = (Funcionario) cbRemoverFunc.getSelectedItem();
       f.getFuncionario().remove(f);
 
       
       
       
    }//GEN-LAST:event_btnRemoverFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public void initComboFuncionario(){
        //FuncionarioRepositorio fr = new FuncionarioDAO();
        List<Funcionario> func = fr.getTodosFuncionarios();
        for(Funcionario f : func ){
            
            cbRemoverFunc.addItem(f.getNome());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFornecedor;
    private javax.swing.JButton btnLimparTempa;
    private javax.swing.JButton btnListFornecedor;
    private javax.swing.JButton btnRemoverFunc;
    private javax.swing.JButton btnTelaInicial;
    private javax.swing.JComboBox<String> cbRemoverFunc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaFuncionarios;
    // End of variables declaration//GEN-END:variables
}
