package View.Livro;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import DAO.LivroNovoListDAO;
import DAO.LivroUsadoListDAO;
import Repositorio.LivroNovoRepositorio;
import Repositorio.LivroUsadoRepositorio;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import models.Livro;
import models.LivroNovo;
import models.LivroUsado;
        

/**
 *
 * @author LRodrigues
 */
public class AddLivroView extends javax.swing.JFrame {
    private LivroNovoListDAO livroNovoDAO =  new LivroNovoListDAO();
      private LivroUsadoListDAO livroUsadoDAO =  new LivroUsadoListDAO();
    /**
     * Creates new form TelaAdicionarPaciente
     */
    public AddLivroView() {
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblValorLivroNovo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtValorLivro = new javax.swing.JTextField();
        lblEdicaoLivro = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        txtLocalEditoraLivro = new javax.swing.JTextField();
        txtAutorLivro = new javax.swing.JTextField();
        txtTituloLivro = new javax.swing.JTextField();
        txtEditoraLivro = new javax.swing.JTextField();
        txtNEdicaoLivro = new javax.swing.JTextField();
        lblAutorDoLivro = new javax.swing.JLabel();
        txtISBNLivro = new javax.swing.JTextField();
        lblTituloLivro = new javax.swing.JLabel();
        btnAddLivro = new javax.swing.JButton();
        lblEditoraLivro = new javax.swing.JLabel();
        lblCadatrarLivro = new javax.swing.JLabel();
        btnLivroUsado = new javax.swing.JRadioButton();
        btnLivroNovo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setInheritsPopupMenu(true);

        lblValorLivroNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValorLivroNovo.setText("Valor do Livro:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Local da Editora:");

        txtValorLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorLivroActionPerformed(evt);
            }
        });

        lblEdicaoLivro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEdicaoLivro.setText("Nº de Edição do Livro:");

        lblISBN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblISBN.setText("ISBN do Livro:");

        lblAutorDoLivro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAutorDoLivro.setText("Autor do Livro:");

        lblTituloLivro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTituloLivro.setText("Titulo do Livro:");

        btnAddLivro.setText("Adicionar Livro");
        btnAddLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLivroAction(evt);
            }
        });

        lblEditoraLivro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEditoraLivro.setText("Editora do Livro:");

        lblCadatrarLivro.setBackground(new java.awt.Color(255, 255, 255));
        lblCadatrarLivro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCadatrarLivro.setText("Cadastrar Livro");

        btnLivroUsado.setText("Livro Usado");
        btnLivroUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivroUsadoActionPerformed(evt);
            }
        });

        btnLivroNovo.setText("Livro Novo");
        btnLivroNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivroNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCadatrarLivro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnLivroUsado)
                        .addGap(47, 47, 47)
                        .addComponent(btnLivroNovo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnAddLivro)))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblAutorDoLivro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAutorLivro))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTituloLivro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblISBN)
                            .addGap(18, 18, 18)
                            .addComponent(txtISBNLivro))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEditoraLivro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEditoraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLocalEditoraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblEdicaoLivro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNEdicaoLivro))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblValorLivroNovo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtValorLivro)))
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblCadatrarLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLivroUsado)
                    .addComponent(btnLivroNovo))
                .addGap(27, 27, 27)
                .addComponent(btnAddLivro)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAutorDoLivro))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTituloLivro))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblEditoraLivro)
                        .addComponent(txtEditoraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(txtLocalEditoraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblEdicaoLivro)
                        .addComponent(txtNEdicaoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtISBNLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblISBN, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblValorLivroNovo)
                        .addComponent(txtValorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLivroNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivroNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLivroNovoActionPerformed

    private void btnLivroUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivroUsadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLivroUsadoActionPerformed

    private void btnAddLivroAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLivroAction
        String autorLivro =  txtAutorLivro.getText();
        String tituloLivro = txtTituloLivro.getText();
        String editoraLivro = txtEditoraLivro.getText();
        String localEditora = txtLocalEditoraLivro.getText();
        String edicaoLivro = txtNEdicaoLivro.getText();
        String ISBNLivro =  txtISBNLivro.getText();
        double precoLivro =  Double.parseDouble(txtValorLivro.getText());
        //LivroNovoRepositorio livroNovoRepositorio = new LivroNovoListDAO();
        Livro book = new LivroNovo((float) precoLivro, autorLivro, tituloLivro, editoraLivro, localEditora, edicaoLivro, ISBNLivro);
        Livro book1 = new LivroUsado((float) precoLivro, autorLivro, tituloLivro, editoraLivro, localEditora, edicaoLivro, ISBNLivro);
        if(btnLivroNovo.isSelected()){
            livroNovoDAO.addLivroNovo((LivroNovo) book);
        }else if(btnLivroUsado.isSelected()){
            livroUsadoDAO.addLivroUsado((LivroUsado) book1);
        }
        limparTela();

    }//GEN-LAST:event_btnAddLivroAction

    private void txtValorLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorLivroActionPerformed

    
    
    public void limparTela(){
        txtAutorLivro.setText("");
        txtEditoraLivro.setText("");
        txtISBNLivro.setText("");
        txtLocalEditoraLivro.setText("");
        txtNEdicaoLivro.setText("");
        txtTituloLivro.setText("");
        txtValorLivro.setText("");
    }
    //    private LivroUsado livroUsadoInstacia;  
//    public void verificandoOpcaoInvalidaCombo(){
//       // if(jComboBoxTempo.getSelectedItem().equals("<Selecione uma da opções>")){
//            JOptionPane.showMessageDialog(null,"OPÇÃO INVÁLIDA, SELECIONE UM TEMPO DE USO VÁLIDO!", null, WIDTH );
//      //  }else{
//       //     JOptionPane.showMessageDialog(null,"OPÇÃO VÁLIDA", null, WIDTH );
//     //  }
//            
//    }
    /**
     * @param args the command line arguments
     */
    
      public void mostrarMensagem(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLivroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLivroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLivroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLivroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLivroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLivro;
    private javax.swing.JRadioButton btnLivroNovo;
    private javax.swing.JRadioButton btnLivroUsado;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAutorDoLivro;
    private javax.swing.JLabel lblCadatrarLivro;
    private javax.swing.JLabel lblEdicaoLivro;
    private javax.swing.JLabel lblEditoraLivro;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblTituloLivro;
    private javax.swing.JLabel lblValorLivroNovo;
    private javax.swing.JTextField txtAutorLivro;
    private javax.swing.JTextField txtEditoraLivro;
    private javax.swing.JTextField txtISBNLivro;
    private javax.swing.JTextField txtLocalEditoraLivro;
    private javax.swing.JTextField txtNEdicaoLivro;
    private javax.swing.JTextField txtTituloLivro;
    private javax.swing.JTextField txtValorLivro;
    // End of variables declaration//GEN-END:variables
}
