/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Livro;

import Controller.ListLivroController;
import DAO.EstoqueDAO;
import DAO.LivroNovoListDAO;
import DAO.LivroUsadoListDAO;
import Repositorio.LivroUsadoRepositorio;
import View.JFTelaInicial;
import java.awt.event.ActionListener;
import java.util.Comparator;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.Livro;
import models.LivroNovo;
import models.LivroUsado;

/**
 *
 * @author LRodrigues
 */
public class JFLivroList extends javax.swing.JFrame {

    
    private LivroUsadoListDAO livroUsadoListDAO =  new LivroUsadoListDAO();
    private EstoqueDAO estoqueDAO = new EstoqueDAO();
    private ListLivroController livroController;
    
    public JFLivroList() {
     
        
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        btnListarLivrosNovos = new javax.swing.JButton();
        btnListarLivrosUsados = new javax.swing.JButton();
        btnGetLivros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaListar = new javax.swing.JTextArea();
        btnLimparTela = new javax.swing.JButton();
        btnPaginaInicial = new javax.swing.JButton();
        btnAddLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnListarLivrosNovos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnListarLivrosNovos.setText("LISTAR LIVROS NOVOS");

        btnListarLivrosUsados.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnListarLivrosUsados.setText("LISTAR LIVROS USADOS");

        btnGetLivros.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGetLivros.setText("LISTAR TODOS OS LIVROS");

        txtAreaListar.setColumns(20);
        txtAreaListar.setRows(5);
        jScrollPane1.setViewportView(txtAreaListar);

        btnLimparTela.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLimparTela.setText("LIMPAR TELA");

        btnPaginaInicial.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPaginaInicial.setText("PÁGINA INICIAL");

        btnAddLivro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddLivro.setText("ADICIONAR LIVRO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGetLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarLivrosUsados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarLivrosNovos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimparTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(btnPaginaInicial)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListarLivrosNovos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListarLivrosUsados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGetLivros)
                        .addGap(16, 16, 16)
                        .addComponent(btnLimparTela))
                    .addComponent(jScrollPane1))
                .addGap(40, 40, 40)
                .addComponent(btnPaginaInicial)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        public void exbirTela(){
        this.setVisible(true);
    }
                
    public void listarTodosLivros(List<LivroNovo> livroNovos, List<LivroUsado> livroUsados){
               for(LivroUsado livroUsado : livroUsados){
               txtAreaListar.append(livroUsado.toString()+"\n");       
       }
            for(LivroNovo livroNovo : livroNovos){
              txtAreaListar.append(livroNovo.toString()+"\n"); 
       } 
    }
    
    public void listarLivrosNovos(List<LivroNovo> livroNovos){

        for(LivroNovo livroNovo : livroNovos){
        txtAreaListar.append(livroNovo.toString()+"\n");       
       }
    }
    
     public void listarLivrosUsados(List<LivroUsado> livroUsados){
 
       for(LivroUsado livroUsado : livroUsados){
           txtAreaListar.append(livroUsado.toString()+"\n");       
       }
    }
     
      public void addAcaoListarTodosLivros(ActionListener acao){
        btnGetLivros.addActionListener(acao);
    }
      
     public void limparTela(){
         txtAreaListar.setText("");
    }    
    
     public void addAcaoLimparTela(ActionListener acao){
         
         btnLimparTela.addActionListener(acao);
     }
     
      public void addAcaoListarLivrosUsado(ActionListener acao){
        btnListarLivrosUsados.addActionListener(acao);
    }
      
    public void addAcaoListarLivrosNovo(ActionListener acao){
        btnListarLivrosNovos.addActionListener(acao);
    }
    
      public void addAcaoTelaAddLivro(ActionListener acao){
        btnAddLivro.addActionListener(acao);
    }
      
    public void addAcaoTelaIniciar(ActionListener acao){  
        btnPaginaInicial.addActionListener(acao);
    }
   
      public void mostrarMensagem(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
      public void fecharTela(){
          this.dispose();
      }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddLivro;
    private javax.swing.JButton btnGetLivros;
    private javax.swing.JButton btnLimparTela;
    private javax.swing.JButton btnListarLivrosNovos;
    private javax.swing.JButton btnListarLivrosUsados;
    private javax.swing.JButton btnPaginaInicial;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaListar;
    // End of variables declaration//GEN-END:variables
}
