/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Livro;

import DAO.EstoqueDAO;
import DAO.LivroNovoListDAO;
import DAO.LivroUsadoListDAO;
import Repositorio.LivroUsadoRepositorio;
import View.JFEstoque;
import java.util.Comparator;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.Livro;
import models.LivroNovo;
import models.LivroUsado;

/**
 *
 * @author LRodrigues
 */
public class JFLivroList extends javax.swing.JFrame {

    private LivroNovoListDAO livroNovoListDAO = new LivroNovoListDAO();
    private LivroUsadoListDAO livroUsadoListDAO =  new LivroUsadoListDAO();
    private EstoqueDAO estoqueDAO = new EstoqueDAO();
    
    public JFLivroList() {
     
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        btnListarLivrosNovos = new javax.swing.JButton();
        btnListarLivrosUsados = new javax.swing.JButton();
        btnGetLivros = new javax.swing.JButton();
        tbnOrdemAlfabetica = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaListar = new javax.swing.JTextArea();
        btnLimparTela = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnListarLivrosNovos.setText("Listar Livros Novos");
        btnListarLivrosNovos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLivrosNovosActionPerformed(evt);
            }
        });

        btnListarLivrosUsados.setText("Lista Livros Usados");
        btnListarLivrosUsados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarLivrosUsadosActionPerformed(evt);
            }
        });

        btnGetLivros.setText("Listar Todos os Livros");
        btnGetLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetLivrosActionPerformed(evt);
            }
        });

        tbnOrdemAlfabetica.setText("Listar por OrdemAlfabética");
        tbnOrdemAlfabetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnOrdemAlfabeticaActionPerformed(evt);
            }
        });

        txtAreaListar.setColumns(20);
        txtAreaListar.setRows(5);
        jScrollPane1.setViewportView(txtAreaListar);

        btnLimparTela.setText("Limpar Tela");
        btnLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTelaActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbnOrdemAlfabetica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGetLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarLivrosUsados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarLivrosNovos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimparTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(370, 370, 370))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListarLivrosNovos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListarLivrosUsados)
                        .addGap(18, 18, 18)
                        .addComponent(btnGetLivros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbnOrdemAlfabetica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimparTela))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarLivrosUsadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLivrosUsadosActionPerformed
     
         livroUsadoListDAO.getTodosLivrosUsados().sort((new Comparator<LivroUsado>() {
             @Override
             public int compare(LivroUsado o1, LivroUsado o2) {
                  return o1.getIsbn().compareTo(o2.getIsbn());    
             }
        
       }));
       for(LivroUsado livroUsado : livroUsadoListDAO.getTodosLivrosUsados()){
           txtAreaListar.append(livroUsado.toString()+"\n");       
       }
    }//GEN-LAST:event_btnListarLivrosUsadosActionPerformed

    private void btnGetLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetLivrosActionPerformed
      
         for(LivroNovo livroNovo : livroNovoListDAO.getTodosLivrosNovos()){
             for(LivroUsado livroUsado : livroUsadoListDAO.getTodosLivrosUsados()){
           txtAreaListar.append(livroNovo.toString()+"\n"); 
           txtAreaListar.append(livroUsado.toString()+"\n");       
       }
       }
    }//GEN-LAST:event_btnGetLivrosActionPerformed

    private void btnListarLivrosNovosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLivrosNovosActionPerformed
       livroNovoListDAO.getTodosLivrosNovos().sort((new Comparator<LivroNovo>() {
           @Override
           public int compare(LivroNovo o1, LivroNovo o2) {

               return o1.getIsbn().compareTo(o2.getIsbn());      
           }
       }));
       for(LivroNovo livroNovo : livroNovoListDAO.getTodosLivrosNovos()){
           txtAreaListar.append(livroNovo.toString()+"\n");       
       }
    }//GEN-LAST:event_btnListarLivrosNovosActionPerformed

    private void btnLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTelaActionPerformed
        // TODO add your handling code here:
        txtAreaListar.setText("");
        
    }//GEN-LAST:event_btnLimparTelaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
      JFEstoque telaEstoque = new JFEstoque();
        telaEstoque.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void tbnOrdemAlfabeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnOrdemAlfabeticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbnOrdemAlfabeticaActionPerformed
    
     private JComboBox<LivroUsado> jComboBox = new javax.swing.JComboBox<>();   
     public void precherComboTempo(){
         //List<LivroUsado> listaLivrosUsado = new LivroUsadoListDAO;
     }
//   public void verificandoOpcaoInvalidaCombo(){
//
//        if(jComboBoxTempo.getSelectedItem().equals("<Selecione uma da opções>")){
//            JOptionPane.showMessageDialog(null,"OPÇÃO INVÁLIDA, SELECIONE UM TEMPO DE USO VÁLIDO!", null, WIDTH );
//        }else{
//            JOptionPane.showMessageDialog(null,"OPÇÃO VÁLIDA", null, WIDTH );
//        }
//
////        if(jComboBoxTempo.getSelectedItem().equals("<Selecione uma da opções>")){
////            JOptionPane.showMessageDialog(null,"OPÇÃO INVÁLIDA, SELECIONE UM TEMPO DE USO VÁLIDO!", null, WIDTH );
////        }else{
////            JOptionPane.showMessageDialog(null,"OPÇÃO VÁLIDA", null, WIDTH );
////        }
//
//            
//    }
    /**
     * @param args the command line arguments
     */
     
    
      public void mostrarMensagem(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLivroList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLivroList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLivroList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLivroList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLivroList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetLivros;
    private javax.swing.JButton btnLimparTela;
    private javax.swing.JButton btnListarLivrosNovos;
    private javax.swing.JButton btnListarLivrosUsados;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tbnOrdemAlfabetica;
    private javax.swing.JTextArea txtAreaListar;
    // End of variables declaration//GEN-END:variables
}
